version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: anonymous-voice-chat-server
    ports:
      - "8080:8080" # Map host port 8080 to container port 8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlite:/app/data/data.db
    volumes:
      - ./src/main/resources/data:/app/data # Mount the SQLite database folder
    depends_on:
      - db
    restart: always

  db:
    image: nouchka/sqlite3:latest # Use a lightweight SQLite Docker image
    container_name: sqlite-db
    volumes:
      - ./src/main/resources/data:/app/data # Persist SQLite database files
    restart: always